#---
#- name: Add Docker GPG apt Key
#    apt_key:
#      url: https://download.docker.com/linux/ubuntu/gpg
#      state: present
#
#- name: Add Docker Repository
#  apt_repository:
#    repo: deb https://download.docker.com/linux/ubuntu focal stable
#    state: present
#
#- name: Update apt and install docker-ce
#  apt:
#    name: docker-ce
#    state: latest
#    update_cache: true
#
#- name: Install Docker Module for Python
#  pip:
#    name: docker
#
---
- name: Add Docker GPG key using apt
  apt:
    deb: "https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    install_recommends: no
    update_cache: yes
    allow_unauthenticated: yes
    signed_by: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker Repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Install Docker Module for Python
  pip:
    name: docker