---
- name: Créer le répertoire Traefik
  file:
    path: /opt/traefik
    state: directory

- name: Vérification existence du traefik-network
  shell: docker network inspect traefik-network
  register: network_check
  ignore_errors: yes

- name: Créer le network traefik-network
  shell: docker network create -d bridge traefik-network
  when: network_check.rc != 0

- name: Créer le fichier docker-compose de Traefik
  copy:
    dest: /opt/traefik/docker-compose.yml
    content: |
      version: '3.3'
      services:
        traefik:
          image: traefik:v3.3
          command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
          ports:
            - "80:80"
            - "8080:8080" # Traefik dashboard
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
          networks:
            - traefik-network
            
      networks:
        traefik-network:
          external: true
          driver: bridge

- name: Lancer Traefik
  shell: docker-compose up -d
  args:
    chdir: /opt/traefik
