---
- name: Créer le répertoire Traefik
  file:
    path: /opt/traefik
    state: directory

- name: Créer le fichier docker-compose de Traefik
  copy:
    dest: /opt/traefik/docker-compose.yml
    content: |
      version: '3.3'
      services:
        traefik:
          image: traefik:v2.10
          container_name: traefik
          command:
            - "--api.insecure=true"
            - "--providers.docker"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
            - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
            - "--certificatesresolvers.myresolver.acme.email=example@example.com" 
            - "--certificatesresolvers.myresolver.acme.storage=acme.json"
          ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./acme.json:/acme.json

- name: Lancer Traefik
  shell: docker-compose up -d
  args:
    chdir: /opt/traefik
