- name: Create app directory
  file:
    path: /opt/app-malveillante
    state: directory

- name: Copy application files
  copy:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: /opt/app-malveillante/
  with_items:
    - front-malveillant
    - api-malveillante
    - docker-compose.yml

- name: Deploy with Docker Compose
  shell: docker-compose up -d
  args:
    chdir: /opt/app-malveillante