---
- hosts: k8s_servers
  become: true
  vars:
    app_name: app-malveillante

  pre_tasks:
    - name: Install pip for Python3
      package:
        name: python3-pip
        state: present

    - name: Install Python Kubernetes module
      pip:
        name: kubernetes
        state: present

    - name: Verify Kubernetes module installation
      command: python3 -c "import kubernetes"
      changed_when: false

  roles:
    - ../roles/kubernetes
#    - ../roles/docker
#    - ../roles/traefik
#    - ../roles/project_manager
#    - ../roles/monitoring
