---
- hosts: k8s_servers
  become: true
  vars:
    app_name: app-malveillante
  roles:
    - ../roles/kubernetes
#    - ../roles/docker
#    - ../roles/traefik
#    - ../roles/project_manager
#    - ../roles/monitoring
