---
- hosts: k8s_servers
  become: true
  vars:
    app_name: app-malveillante

  pre_tasks:
    - name: Install Python Kubernetes packages using APT
      apt:
        name:
          - python3-kubernetes
          - python3-openshift
        state: present
        update_cache: yes

    - name: Verify Kubernetes module installation
      command: python3 -c "import kubernetes"
      changed_when: false

  roles:
    - ../roles/kubernetes
#    - ../roles/docker
#    - ../roles/traefik
#    - ../roles/project_manager
#    - ../roles/monitoring
