name: Ansible Deployment
on:
  push:
    branches: [ main ]

env:
  ANSIBLE_HOST_KEY_CHECKING: "False"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection install kubernetes.core --force

      - name: Install Kubernetes Python client
        run: |
          pip install kubernetes
          pip show kubernetes

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no root@185.98.138.237 "echo 'Connexion réussie'"

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory/hosts.ini playbooks/site.yml
