name: Ansible Deployment
on:
  push:
    branches: [ main ]

env:
  ANSIBLE_HOST_KEY_CHECKING: "False"

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine/ansible
      volumes:
        - /__w/app-malveillante/app-malveillante:/app
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#      - name: Setup kubeconfig
#        run: |
#          mkdir -p ~/.kube
#          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
#          chmod 600 ~/.kube/config

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no root@185.98.138.237 "echo 'Connexion réussie'"

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory/hosts.ini playbooks/site.yml
